[package]
name = "vcc"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.24.0"
eframe = "0.24.0"
trie-rs = "0.1.1"
sqlite = "0.32.0"

[profile.release]
opt-level = 3
debug = false
split-debuginfo = '...'  # Platform-specific.
debug-assertions = false
overflow-checks = false
panic = 'unwind'
incremental = false
codegen-units = 16
rpath = false
strip = "symbols"
lto = "fat"
target-cpu = "native"
